### ISSUE TITLE
Dashboard fails to create

### ISSUE THREAD

**Issue by SpyderDave** [GoogleCloudPlatform/terraform-splunk-log-export#16]
Hey there. Wondering if someone could assist with deploying this solution.

I got everything working with the exception of the Dashboard which fails to create and I am quite stuck.

  + dataflow_log_export_dashboard = (known after apply)
google_monitoring_dashboard.splunk-export-pipeline-dashboard: Creating...
╷
│ Error: Error creating Dashboard: googleapi: Error 400: Field mosaicLayout.tiles[2].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'custom.googleapis.com/dataflow/outbound-successful-events'.
│ Field mosaicLayout.tiles[5].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'custom.googleapis.com/dataflow/outbound-successful-events'.
│ Field mosaicLayout.tiles[7].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'custom.googleapis.com/dataflow/http-server-error-requests'.
│ Field mosaicLayout.tiles[8].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'custom.googleapis.com/dataflow/http-invalid-requests'.
│ Field mosaicLayout.tiles[12].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'custom.googleapis.com/dataflow/total-failed-messages'.
│ Field mosaicLayout.tiles[14].widget.scorecard.timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'custom.googleapis.com/dataflow/outbound-successful-events'.
│
│   with google_monitoring_dashboard.splunk-export-pipeline-dashboard,
│   on monitoring.tf line 22, in resource "google_monitoring_dashboard" "splunk-export-pipeline-dashboard":
│   22: resource "google_monitoring_dashboard" "splunk-export-pipeline-dashboard" {
│

**Comment by SpyderDave** [comment]
My bad

**Comment by rarsan** [comment]
Thx for filing this issue @SpyderDave .
This seems like a dependency issue. Other resources, namely the job itself, should still deploy successfully.
To try and fix this:
In `monitoring.tf`, could you add a `depends_on` clause in dashboard resource definition, as follows:

```
resource "google_monitoring_dashboard" "splunk-export-pipeline-dashboard" {
  project = local.scoping_project

  depends_on = [
    google_dataflow_job.dataflow_job
  ]

  dashboard_json = <<EOF
# Dashboard JSON (redacted here for brevity)
  EOF
}
```

Please do report if this resolves it. Thanks.

**Comment by SpyderDave** [comment]
You are correct, everything else seems to work properly.
The depends_on did not seem to fix it.

**Comment by rarsan** [comment]
I updated dashboard to fetch user metrics from `dataflow.googleapis.com` instead of `custom.googleapis.com`. The latter has a project-wide limit of only 100 custom metrics[1] which you might be hitting.

Please pull latest code and give this another try.

[1] https://cloud.google.com/dataflow/docs/guides/using-cloud-monitoring#custom_metrics

**Comment by SpyderDave** [comment]
Worked like a charm and I can see the "Splunk Log Export Ops" Dashboard in Cloud Monitoring!

Thanks so much for this.

I also had a couple of other questions about this solution.  Is there a way we could communicate (Chat? Email?)?  I will gladly help as well..

**Comment by rarsan** [comment]
Awesome. You're welcome! Closing this ticket.
Happy to chat more. Send me a note at my username @ google.com
