### ISSUE TITLE
 Terraform generates 600 lines of json in plan each time.

### ISSUE THREAD

**Issue by agutta** [GoogleCloudPlatform/terraform-splunk-log-export#17]
Monitoring dashboard resource relies on dynamic JSON, Terraform thinks it's a resource to be updated with every plan/apply.
This is not consequential since it's updating the dashboard but without any net effect. But the plan is 600 lines and it makes looking at real changes hard to validate.

**Comment by Lakhtenkov-iv** [comment]
This is an issue of [google_monitoring_dashboard](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_dashboard) resource of `google` terraform provider that is discussing here: https://github.com/hashicorp/terraform-provider-google/issues/7242. I believe that not too much could be done within the module.
The single option is that we have is to add lifecycle hook `ignore_changes`, but this would prevent of dashboard update in case of module version bump up.
