### ISSUE TITLE
Not pulling in access transparency logs

### ISSUE THREAD

**Issue by lanceblais** [GoogleCloudPlatform/terraform-splunk-log-export#42]
Hello!

We're using this terraform module with GCP's cloud audit logs. We're using the `google_logging_organization_sink` and everything is working great.

We did however notice that we aren't getting the [Access Transparency Logs](https://cloud.google.com/cloud-provider-access-management/access-transparency/docs/reading-logs) come through.

e.g.

```
log_filter="resource.labels.project_id=\"SOMEPROJECT\" AND log_name:\"projects/SOMEPROJECT/logs/cloudaudit.googleapis.com\"
```

Has anyone encountered this before? Do we need to provide more IAM permissions to something?

Anything helps, thanks!

**Comment by rarsan** [comment]
Hey @lanceblais is this still an issue?

Have you validated in Logs Explorer that access transparency logs exist in the `_Required` bucket? To do that, you need the Private Logs Viewer role.

While not related to this Terraform module directly, I suggest removing the `resource.labels.project_id` condition from your log filter. The audited accesses could be for organization-level resources where that label `project_id` is not populated (instead `organization_id` is populated).
